<?php

require_once __DIR__ . '/config/config.php';
$pageTitle = 'FAQ';
require_once __DIR__ . '/includes/header.php';
?>
<section class="shop-intro"><div class="container py-5"><p class="eyebrow mb-2">Good to know</p><h1 class="section-title mb-2">Frequently asked questions</h1><p class="text-secondary mb-0">A few useful answers before your piece begins its journey.</p></div></section>
<section class="container py-5"><div class="row g-5"><div class="col-lg-4"><p class="eyebrow">Help desk</p><h2 class="section-title h1">Take your time.</h2><p class="text-secondary">Still curious? <a class="text-link" href="<?= e(url('contact.php')) ?>">Send us a note.</a></p></div><div class="col-lg-7 offset-lg-1"><div class="accordion faq-accordion" id="faqAccordion"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqOne" aria-expanded="true" aria-controls="faqOne">How do I choose a color?</button></h3><div id="faqOne" class="accordion-collapse collapse show" data-bs-parent="#faqAccordion"><div class="accordion-body text-secondary">Each product lists the available colors and, where relevant, the additional price and stock for that choice.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqTwo" aria-expanded="false" aria-controls="faqTwo">Are the Dastkars ready to wear?</button></h3><div id="faqTwo" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body text-secondary">Yes. We select pieces for a comfortable drape and include simple care guidance with every order.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqThree" aria-expanded="false" aria-controls="faqThree">How long does delivery take?</button></h3><div id="faqThree" class="accordion-collapse collapse" data-bs-parent="#faqAccordion"><div class="accordion-body text-secondary">Delivery timing depends on destination. We confirm the details with you after a Cash on Delivery order is placed.</div></div></div></div></div></div></section>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
